server_name: nats-3  # <--- 修改这里
port: 4222
http_port: 8224

cluster {
  name: my-game-cluster
  port: 6222
  routes = [
    "nats://192.168.1.11:6222",
    "nats://192.168.1.12:6222",
    "nats://192.168.1.13:6222"
  ]
}