// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.4
// source: slots_define.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectType int32

const (
	CollectType_COLLECT_NONE     CollectType = 0 // 改名：加前缀
	CollectType_COLLECT_BONUS    CollectType = 1
	CollectType_COLLECT_FREESPIN CollectType = 2
)

// Enum value maps for CollectType.
var (
	CollectType_name = map[int32]string{
		0: "COLLECT_NONE",
		1: "COLLECT_BONUS",
		2: "COLLECT_FREESPIN",
	}
	CollectType_value = map[string]int32{
		"COLLECT_NONE":     0,
		"COLLECT_BONUS":    1,
		"COLLECT_FREESPIN": 2,
	}
)

func (x CollectType) Enum() *CollectType {
	p := new(CollectType)
	*p = x
	return p
}

func (x CollectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectType) Descriptor() protoreflect.EnumDescriptor {
	return file_slots_define_proto_enumTypes[0].Descriptor()
}

func (CollectType) Type() protoreflect.EnumType {
	return &file_slots_define_proto_enumTypes[0]
}

func (x CollectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectType.Descriptor instead.
func (CollectType) EnumDescriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{0}
}

// 中奖类型
type WinType int32

const (
	WinType_WIN_NONE   WinType = 0
	WinType_WIN_MINOR  WinType = 1 // 小奖 （小三档第一档）
	WinType_WIN_MEDIUM WinType = 2 // 中奖 （小三档第二档）
	WinType_WIN_BIG    WinType = 3 // 大奖 （小三档第三档）
	WinType_WIN_MEGA   WinType = 4 // 巨大
	WinType_WIN_EPIC   WinType = 5 // 史诗
	WinType_WIN_SUPER  WinType = 6 // 超级
)

// Enum value maps for WinType.
var (
	WinType_name = map[int32]string{
		0: "WIN_NONE",
		1: "WIN_MINOR",
		2: "WIN_MEDIUM",
		3: "WIN_BIG",
		4: "WIN_MEGA",
		5: "WIN_EPIC",
		6: "WIN_SUPER",
	}
	WinType_value = map[string]int32{
		"WIN_NONE":   0,
		"WIN_MINOR":  1,
		"WIN_MEDIUM": 2,
		"WIN_BIG":    3,
		"WIN_MEGA":   4,
		"WIN_EPIC":   5,
		"WIN_SUPER":  6,
	}
)

func (x WinType) Enum() *WinType {
	p := new(WinType)
	*p = x
	return p
}

func (x WinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WinType) Descriptor() protoreflect.EnumDescriptor {
	return file_slots_define_proto_enumTypes[1].Descriptor()
}

func (WinType) Type() protoreflect.EnumType {
	return &file_slots_define_proto_enumTypes[1]
}

func (x WinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WinType.Descriptor instead.
func (WinType) EnumDescriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{1}
}

// 基础信息
type BaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                    // 老虎机ID
	HasPlayed     bool                   `protobuf:"varint,2,opt,name=hasPlayed,proto3" json:"hasPlayed,omitempty"`      // 是否玩过
	UserBet       int64                  `protobuf:"varint,3,opt,name=userBet,proto3" json:"userBet,omitempty"`          // 玩家自选倍率
	DefaultBet    int64                  `protobuf:"varint,4,opt,name=defaultBet,proto3" json:"defaultBet,omitempty"`    // 默认推荐倍率
	BetArray      []int32                `protobuf:"varint,5,rep,packed,name=betArray,proto3" json:"betArray,omitempty"` // 押注数组
	BaseMoney     int64                  `protobuf:"varint,6,opt,name=baseMoney,proto3" json:"baseMoney,omitempty"`      // 基础押注金钱
	ReelSpeed     int32                  `protobuf:"varint,7,opt,name=reelSpeed,proto3" json:"reelSpeed,omitempty"`      // 转轴速度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfo) Reset() {
	*x = BaseInfo{}
	mi := &file_slots_define_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfo) ProtoMessage() {}

func (x *BaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfo.ProtoReflect.Descriptor instead.
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{0}
}

func (x *BaseInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseInfo) GetHasPlayed() bool {
	if x != nil {
		return x.HasPlayed
	}
	return false
}

func (x *BaseInfo) GetUserBet() int64 {
	if x != nil {
		return x.UserBet
	}
	return 0
}

func (x *BaseInfo) GetDefaultBet() int64 {
	if x != nil {
		return x.DefaultBet
	}
	return 0
}

func (x *BaseInfo) GetBetArray() []int32 {
	if x != nil {
		return x.BetArray
	}
	return nil
}

func (x *BaseInfo) GetBaseMoney() int64 {
	if x != nil {
		return x.BaseMoney
	}
	return 0
}

func (x *BaseInfo) GetReelSpeed() int32 {
	if x != nil {
		return x.ReelSpeed
	}
	return 0
}

type GameStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurGameStage  int32                  `protobuf:"varint,1,opt,name=curGameStage,proto3" json:"curGameStage,omitempty"`   // 当前的游戏阶段
	NextGameStage int32                  `protobuf:"varint,2,opt,name=nextGameStage,proto3" json:"nextGameStage,omitempty"` // 下一个游戏阶段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStage) Reset() {
	*x = GameStage{}
	mi := &file_slots_define_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStage) ProtoMessage() {}

func (x *GameStage) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStage.ProtoReflect.Descriptor instead.
func (*GameStage) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{1}
}

func (x *GameStage) GetCurGameStage() int32 {
	if x != nil {
		return x.CurGameStage
	}
	return 0
}

func (x *GameStage) GetNextGameStage() int32 {
	if x != nil {
		return x.NextGameStage
	}
	return 0
}

// 转轴更新的数据
type ReelsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReelVersion   int32                  `protobuf:"varint,1,opt,name=reelVersion,proto3" json:"reelVersion,omitempty"` // 转轴版本号
	ReelArray     []*Int32Array2         `protobuf:"bytes,2,rep,name=reelArray,proto3" json:"reelArray,omitempty"`      // 新转轴
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReelsInfo) Reset() {
	*x = ReelsInfo{}
	mi := &file_slots_define_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReelsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReelsInfo) ProtoMessage() {}

func (x *ReelsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReelsInfo.ProtoReflect.Descriptor instead.
func (*ReelsInfo) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{2}
}

func (x *ReelsInfo) GetReelVersion() int32 {
	if x != nil {
		return x.ReelVersion
	}
	return 0
}

func (x *ReelsInfo) GetReelArray() []*Int32Array2 {
	if x != nil {
		return x.ReelArray
	}
	return nil
}

// 单次摇奖结果
type SpinResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReelsArray    []*Int32Array2         `protobuf:"bytes,1,rep,name=reelsArray,proto3" json:"reelsArray,omitempty"`             // 当次spin使用的转轴, 带有转轴则不会再去匹配预设转轴
	ReelsArrayId  []int32                `protobuf:"varint,2,rep,packed,name=reelsArrayId,proto3" json:"reelsArrayId,omitempty"` // 当次spin使用的预设轴id
	PosInReels    []*Int32Array1         `protobuf:"bytes,3,rep,name=posInReels,proto3" json:"posInReels,omitempty"`             // 当次spin结果在轴中的位置
	Results       []*Int32Array2         `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`                   // 当次spin结果数组展示
	HoldWins      []*Int32Array1         `protobuf:"bytes,5,rep,name=holdWins,proto3" json:"holdWins,omitempty"`                 // 当次spin结果的holdwin数据
	StopInfo      []*Int32Array2         `protobuf:"bytes,6,rep,name=stopInfo,proto3" json:"stopInfo,omitempty"`                 // 当次spin结果的stop信息
	WinInfo       []*SpinResult_WinInfo  `protobuf:"bytes,7,rep,name=winInfo,proto3" json:"winInfo,omitempty"`                   // 当次spin结果的中奖信息
	FixedBet      int64                  `protobuf:"varint,8,opt,name=fixedBet,proto3" json:"fixedBet,omitempty"`                // 关卡固定倍率，如果有当前字段，玩家升级时锁定倍率，不做调整。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinResult) Reset() {
	*x = SpinResult{}
	mi := &file_slots_define_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinResult) ProtoMessage() {}

func (x *SpinResult) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinResult.ProtoReflect.Descriptor instead.
func (*SpinResult) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{3}
}

func (x *SpinResult) GetReelsArray() []*Int32Array2 {
	if x != nil {
		return x.ReelsArray
	}
	return nil
}

func (x *SpinResult) GetReelsArrayId() []int32 {
	if x != nil {
		return x.ReelsArrayId
	}
	return nil
}

func (x *SpinResult) GetPosInReels() []*Int32Array1 {
	if x != nil {
		return x.PosInReels
	}
	return nil
}

func (x *SpinResult) GetResults() []*Int32Array2 {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SpinResult) GetHoldWins() []*Int32Array1 {
	if x != nil {
		return x.HoldWins
	}
	return nil
}

func (x *SpinResult) GetStopInfo() []*Int32Array2 {
	if x != nil {
		return x.StopInfo
	}
	return nil
}

func (x *SpinResult) GetWinInfo() []*SpinResult_WinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *SpinResult) GetFixedBet() int64 {
	if x != nil {
		return x.FixedBet
	}
	return 0
}

// 赔率信息
type PayInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CardsPayInfo       *CardsPayInfo          `protobuf:"bytes,1,opt,name=cardsPayInfo,proto3" json:"cardsPayInfo,omitempty"`             // 卡牌赔率信息
	CombinationPayInfo *CombinationPayInfo    `protobuf:"bytes,2,opt,name=combinationPayInfo,proto3" json:"combinationPayInfo,omitempty"` // 混合卡牌赔率信息
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PayInfo) Reset() {
	*x = PayInfo{}
	mi := &file_slots_define_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayInfo) ProtoMessage() {}

func (x *PayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayInfo.ProtoReflect.Descriptor instead.
func (*PayInfo) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{4}
}

func (x *PayInfo) GetCardsPayInfo() *CardsPayInfo {
	if x != nil {
		return x.CardsPayInfo
	}
	return nil
}

func (x *PayInfo) GetCombinationPayInfo() *CombinationPayInfo {
	if x != nil {
		return x.CombinationPayInfo
	}
	return nil
}

type CardsPayInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            // 卡牌ID
	CardInfo      string                 `protobuf:"bytes,2,opt,name=cardInfo,proto3" json:"cardInfo,omitempty"` // 卡牌赔率信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardsPayInfo) Reset() {
	*x = CardsPayInfo{}
	mi := &file_slots_define_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardsPayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardsPayInfo) ProtoMessage() {}

func (x *CardsPayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardsPayInfo.ProtoReflect.Descriptor instead.
func (*CardsPayInfo) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{5}
}

func (x *CardsPayInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardsPayInfo) GetCardInfo() string {
	if x != nil {
		return x.CardInfo
	}
	return ""
}

type CombinationPayInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // 卡牌ID
	CardInfo      string                 `protobuf:"bytes,2,opt,name=cardInfo,proto3" json:"cardInfo,omitempty"` // 卡牌赔率信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombinationPayInfo) Reset() {
	*x = CombinationPayInfo{}
	mi := &file_slots_define_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinationPayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinationPayInfo) ProtoMessage() {}

func (x *CombinationPayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinationPayInfo.ProtoReflect.Descriptor instead.
func (*CombinationPayInfo) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{6}
}

func (x *CombinationPayInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CombinationPayInfo) GetCardInfo() string {
	if x != nil {
		return x.CardInfo
	}
	return ""
}

// jackpot的数据
type JackPot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Win           int64                  `protobuf:"varint,3,opt,name=win,proto3" json:"win,omitempty"`                 // 某一档大于0 则中了这挡的jackpot
	MinimumBet    int64                  `protobuf:"varint,4,opt,name=minimumBet,proto3" json:"minimumBet,omitempty"`   // 最低押注
	Coefficient   int64                  `protobuf:"varint,5,opt,name=coefficient,proto3" json:"coefficient,omitempty"` // jp的系数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JackPot) Reset() {
	*x = JackPot{}
	mi := &file_slots_define_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JackPot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JackPot) ProtoMessage() {}

func (x *JackPot) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JackPot.ProtoReflect.Descriptor instead.
func (*JackPot) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{7}
}

func (x *JackPot) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *JackPot) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *JackPot) GetWin() int64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *JackPot) GetMinimumBet() int64 {
	if x != nil {
		return x.MinimumBet
	}
	return 0
}

func (x *JackPot) GetCoefficient() int64 {
	if x != nil {
		return x.Coefficient
	}
	return 0
}

// 中大奖翻倍的数据
type BigWinMult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Win           int64                  `protobuf:"varint,1,opt,name=win,proto3" json:"win,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BigWinMult) Reset() {
	*x = BigWinMult{}
	mi := &file_slots_define_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigWinMult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigWinMult) ProtoMessage() {}

func (x *BigWinMult) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigWinMult.ProtoReflect.Descriptor instead.
func (*BigWinMult) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{8}
}

func (x *BigWinMult) GetWin() int64 {
	if x != nil {
		return x.Win
	}
	return 0
}

type SpinUserInfo struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SpinUserBase  *SpinUserInfo_SpinUserBase `protobuf:"bytes,1,opt,name=spinUserBase,proto3" json:"spinUserBase,omitempty"`
	LevelUpInfo   *SpinUserInfo_LevelUpInfo  `protobuf:"bytes,2,opt,name=levelUpInfo,proto3" json:"levelUpInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinUserInfo) Reset() {
	*x = SpinUserInfo{}
	mi := &file_slots_define_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinUserInfo) ProtoMessage() {}

func (x *SpinUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinUserInfo.ProtoReflect.Descriptor instead.
func (*SpinUserInfo) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{9}
}

func (x *SpinUserInfo) GetSpinUserBase() *SpinUserInfo_SpinUserBase {
	if x != nil {
		return x.SpinUserBase
	}
	return nil
}

func (x *SpinUserInfo) GetLevelUpInfo() *SpinUserInfo_LevelUpInfo {
	if x != nil {
		return x.LevelUpInfo
	}
	return nil
}

type SpinResult_WinInfo struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Type          WinType                        `protobuf:"varint,1,opt,name=type,proto3,enum=pb.WinType" json:"type,omitempty"` // 中奖类型
	Win           int32                          `protobuf:"varint,2,opt,name=win,proto3" json:"win,omitempty"`                   // 钱
	KindType      int32                          `protobuf:"varint,3,opt,name=kindType,proto3" json:"kindType,omitempty"`         //
	Lines         []*SpinResult_WinInfo_LineInfo `protobuf:"bytes,4,rep,name=lines,proto3" json:"lines,omitempty"`                // 中奖线
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinResult_WinInfo) Reset() {
	*x = SpinResult_WinInfo{}
	mi := &file_slots_define_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinResult_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinResult_WinInfo) ProtoMessage() {}

func (x *SpinResult_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinResult_WinInfo.ProtoReflect.Descriptor instead.
func (*SpinResult_WinInfo) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SpinResult_WinInfo) GetType() WinType {
	if x != nil {
		return x.Type
	}
	return WinType_WIN_NONE
}

func (x *SpinResult_WinInfo) GetWin() int32 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *SpinResult_WinInfo) GetKindType() int32 {
	if x != nil {
		return x.KindType
	}
	return 0
}

func (x *SpinResult_WinInfo) GetLines() []*SpinResult_WinInfo_LineInfo {
	if x != nil {
		return x.Lines
	}
	return nil
}

// 中奖线数据结果
type SpinResult_WinInfo_LineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`              // 线ID
	Win           int64                  `protobuf:"varint,2,opt,name=win,proto3" json:"win,omitempty"`            // 单线钱
	Symbol        int32                  `protobuf:"varint,3,opt,name=symbol,proto3" json:"symbol,omitempty"`      // 中奖ID
	Positions     []*Int32Array1         `protobuf:"bytes,4,rep,name=positions,proto3" json:"positions,omitempty"` // 位置信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinResult_WinInfo_LineInfo) Reset() {
	*x = SpinResult_WinInfo_LineInfo{}
	mi := &file_slots_define_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinResult_WinInfo_LineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinResult_WinInfo_LineInfo) ProtoMessage() {}

func (x *SpinResult_WinInfo_LineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinResult_WinInfo_LineInfo.ProtoReflect.Descriptor instead.
func (*SpinResult_WinInfo_LineInfo) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *SpinResult_WinInfo_LineInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpinResult_WinInfo_LineInfo) GetWin() int64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *SpinResult_WinInfo_LineInfo) GetSymbol() int32 {
	if x != nil {
		return x.Symbol
	}
	return 0
}

func (x *SpinResult_WinInfo_LineInfo) GetPositions() []*Int32Array1 {
	if x != nil {
		return x.Positions
	}
	return nil
}

type SpinUserInfo_SpinUserBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurLevel      int32                  `protobuf:"varint,1,opt,name=curLevel,proto3" json:"curLevel,omitempty"`     // 当前等级
	CurExp        int64                  `protobuf:"varint,2,opt,name=curExp,proto3" json:"curExp,omitempty"`         // 当前经验
	NextExp       int64                  `protobuf:"varint,3,opt,name=nextExp,proto3" json:"nextExp,omitempty"`       // 下级经验
	PreExp        int64                  `protobuf:"varint,4,opt,name=preExp,proto3" json:"preExp,omitempty"`         // 前一级经验
	Balance       int64                  `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`       // 用户最终金币数
	PreBalance    int64                  `protobuf:"varint,6,opt,name=preBalance,proto3" json:"preBalance,omitempty"` // 押注前金币数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinUserInfo_SpinUserBase) Reset() {
	*x = SpinUserInfo_SpinUserBase{}
	mi := &file_slots_define_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinUserInfo_SpinUserBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinUserInfo_SpinUserBase) ProtoMessage() {}

func (x *SpinUserInfo_SpinUserBase) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinUserInfo_SpinUserBase.ProtoReflect.Descriptor instead.
func (*SpinUserInfo_SpinUserBase) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{9, 0}
}

func (x *SpinUserInfo_SpinUserBase) GetCurLevel() int32 {
	if x != nil {
		return x.CurLevel
	}
	return 0
}

func (x *SpinUserInfo_SpinUserBase) GetCurExp() int64 {
	if x != nil {
		return x.CurExp
	}
	return 0
}

func (x *SpinUserInfo_SpinUserBase) GetNextExp() int64 {
	if x != nil {
		return x.NextExp
	}
	return 0
}

func (x *SpinUserInfo_SpinUserBase) GetPreExp() int64 {
	if x != nil {
		return x.PreExp
	}
	return 0
}

func (x *SpinUserInfo_SpinUserBase) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *SpinUserInfo_SpinUserBase) GetPreBalance() int64 {
	if x != nil {
		return x.PreBalance
	}
	return 0
}

type SpinUserInfo_LevelUpInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BetDefault     int32                  `protobuf:"varint,1,opt,name=betDefault,proto3" json:"betDefault,omitempty"`         // 默认赔率
	BetArray       []int32                `protobuf:"varint,2,rep,packed,name=betArray,proto3" json:"betArray,omitempty"`      // 押注数组
	Reward         *RewardData            `protobuf:"bytes,3,opt,name=reward,proto3" json:"reward,omitempty"`                  // 升级奖励
	Secret         string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`                  // AD密钥
	Rooms          []int32                `protobuf:"varint,5,rep,packed,name=rooms,proto3" json:"rooms,omitempty"`            // 新解锁关上列表
	IsNewcomerDeal bool                   `protobuf:"varint,6,opt,name=isNewcomerDeal,proto3" json:"isNewcomerDeal,omitempty"` // 是否弹出新手deal
	NeedPopup      bool                   `protobuf:"varint,7,opt,name=needPopup,proto3" json:"needPopup,omitempty"`           // 是否弹出升级弹窗
	CoinsRate      int32                  `protobuf:"varint,8,opt,name=coinsRate,proto3" json:"coinsRate,omitempty"`           // 金币比率
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpinUserInfo_LevelUpInfo) Reset() {
	*x = SpinUserInfo_LevelUpInfo{}
	mi := &file_slots_define_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinUserInfo_LevelUpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinUserInfo_LevelUpInfo) ProtoMessage() {}

func (x *SpinUserInfo_LevelUpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slots_define_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinUserInfo_LevelUpInfo.ProtoReflect.Descriptor instead.
func (*SpinUserInfo_LevelUpInfo) Descriptor() ([]byte, []int) {
	return file_slots_define_proto_rawDescGZIP(), []int{9, 1}
}

func (x *SpinUserInfo_LevelUpInfo) GetBetDefault() int32 {
	if x != nil {
		return x.BetDefault
	}
	return 0
}

func (x *SpinUserInfo_LevelUpInfo) GetBetArray() []int32 {
	if x != nil {
		return x.BetArray
	}
	return nil
}

func (x *SpinUserInfo_LevelUpInfo) GetReward() *RewardData {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *SpinUserInfo_LevelUpInfo) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *SpinUserInfo_LevelUpInfo) GetRooms() []int32 {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *SpinUserInfo_LevelUpInfo) GetIsNewcomerDeal() bool {
	if x != nil {
		return x.IsNewcomerDeal
	}
	return false
}

func (x *SpinUserInfo_LevelUpInfo) GetNeedPopup() bool {
	if x != nil {
		return x.NeedPopup
	}
	return false
}

func (x *SpinUserInfo_LevelUpInfo) GetCoinsRate() int32 {
	if x != nil {
		return x.CoinsRate
	}
	return 0
}

var File_slots_define_proto protoreflect.FileDescriptor

var file_slots_define_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x01,
	0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x61,
	0x73, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68,
	0x61, 0x73, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x42, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x42,
	0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x42, 0x65, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x42,
	0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x62, 0x65, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x1c,
	0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x65, 0x6c, 0x53, 0x70, 0x65, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x72, 0x65, 0x65, 0x6c, 0x53, 0x70, 0x65, 0x65, 0x64, 0x22, 0x55, 0x0a, 0x09, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63,
	0x75, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6e,
	0x65, 0x78, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x22, 0x5c, 0x0a, 0x09, 0x52, 0x65, 0x65, 0x6c, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x2d, 0x0a, 0x09, 0x72, 0x65, 0x65, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x32, 0x52, 0x09, 0x72, 0x65, 0x65, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x22,
	0xec, 0x04, 0x0a, 0x0a, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2f,
	0x0a, 0x0a, 0x72, 0x65, 0x65, 0x6c, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x32, 0x52, 0x0a, 0x72, 0x65, 0x65, 0x6c, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12,
	0x22, 0x0a, 0x0c, 0x72, 0x65, 0x65, 0x6c, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x65, 0x6c, 0x73, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x49, 0x6e, 0x52, 0x65, 0x65, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74,
	0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x31, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x49, 0x6e, 0x52,
	0x65, 0x65, 0x6c, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x32, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12,
	0x2b, 0x0a, 0x08, 0x68, 0x6f, 0x6c, 0x64, 0x57, 0x69, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x31, 0x52, 0x08, 0x68, 0x6f, 0x6c, 0x64, 0x57, 0x69, 0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x08,
	0x73, 0x74, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x32, 0x52,
	0x08, 0x73, 0x74, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x07, 0x77, 0x69, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x70, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x57, 0x69, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x78, 0x65, 0x64, 0x42, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66,
	0x69, 0x78, 0x65, 0x64, 0x42, 0x65, 0x74, 0x1a, 0x84, 0x02, 0x0a, 0x07, 0x57, 0x69, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x69, 0x6e, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6b, 0x69, 0x6e, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x35, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x2e, 0x57, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x1a, 0x73, 0x0a, 0x08, 0x4c, 0x69, 0x6e,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12,
	0x2d, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x31, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x87,
	0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x0c, 0x63, 0x61,
	0x72, 0x64, 0x73, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x73, 0x50, 0x61, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0c, 0x63, 0x61, 0x72, 0x64, 0x73, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x46, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x12, 0x63, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3a, 0x0a, 0x0c, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x40, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61,
	0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x07, 0x4a, 0x61, 0x63, 0x6b, 0x50,
	0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x77,
	0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x42, 0x65, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x42,
	0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63,
	0x69, 0x65, 0x6e, 0x74, 0x22, 0x1e, 0x0a, 0x0a, 0x42, 0x69, 0x67, 0x57, 0x69, 0x6e, 0x4d, 0x75,
	0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x77, 0x69, 0x6e, 0x22, 0xc8, 0x04, 0x0a, 0x0c, 0x53, 0x70, 0x69, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x41, 0x0a, 0x0c, 0x73, 0x70, 0x69, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x70, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x70,
	0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x0c, 0x73, 0x70, 0x69, 0x6e,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x55, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x70, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x55, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0xae, 0x01, 0x0a, 0x0c, 0x53, 0x70, 0x69,
	0x6e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x75, 0x72,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x45, 0x78, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x75, 0x72, 0x45, 0x78, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x6e, 0x65, 0x78, 0x74, 0x45, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x6e, 0x65, 0x78, 0x74, 0x45, 0x78, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x45, 0x78,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x72, 0x65, 0x45, 0x78, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x65,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70,
	0x72, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x83, 0x02, 0x0a, 0x0b, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x55, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x65, 0x74,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62,
	0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x74,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x62, 0x65, 0x74,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x69,
	0x73, 0x4e, 0x65, 0x77, 0x63, 0x6f, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x61, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73, 0x4e, 0x65, 0x77, 0x63, 0x6f, 0x6d, 0x65, 0x72, 0x44,
	0x65, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x50, 0x6f, 0x70, 0x75, 0x70,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x50, 0x6f, 0x70, 0x75,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x61, 0x74, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x61, 0x74, 0x65, 0x2a,
	0x48, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x0c, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x5f, 0x42, 0x4f, 0x4e, 0x55,
	0x53, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x5f, 0x46,
	0x52, 0x45, 0x45, 0x53, 0x50, 0x49, 0x4e, 0x10, 0x02, 0x2a, 0x6e, 0x0a, 0x07, 0x57, 0x69, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x57, 0x49, 0x4e, 0x5f, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x49, 0x4e, 0x5f, 0x4d, 0x49, 0x4e, 0x4f, 0x52, 0x10,
	0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x49, 0x4e, 0x5f, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x49, 0x4e, 0x5f, 0x42, 0x49, 0x47, 0x10, 0x03, 0x12, 0x0c,
	0x0a, 0x08, 0x57, 0x49, 0x4e, 0x5f, 0x4d, 0x45, 0x47, 0x41, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08,
	0x57, 0x49, 0x4e, 0x5f, 0x45, 0x50, 0x49, 0x43, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x49,
	0x4e, 0x5f, 0x53, 0x55, 0x50, 0x45, 0x52, 0x10, 0x06, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_slots_define_proto_rawDescOnce sync.Once
	file_slots_define_proto_rawDescData []byte
)

func file_slots_define_proto_rawDescGZIP() []byte {
	file_slots_define_proto_rawDescOnce.Do(func() {
		file_slots_define_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slots_define_proto_rawDesc), len(file_slots_define_proto_rawDesc)))
	})
	return file_slots_define_proto_rawDescData
}

var file_slots_define_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_slots_define_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_slots_define_proto_goTypes = []any{
	(CollectType)(0),                    // 0: pb.CollectType
	(WinType)(0),                        // 1: pb.WinType
	(*BaseInfo)(nil),                    // 2: pb.BaseInfo
	(*GameStage)(nil),                   // 3: pb.GameStage
	(*ReelsInfo)(nil),                   // 4: pb.ReelsInfo
	(*SpinResult)(nil),                  // 5: pb.SpinResult
	(*PayInfo)(nil),                     // 6: pb.PayInfo
	(*CardsPayInfo)(nil),                // 7: pb.CardsPayInfo
	(*CombinationPayInfo)(nil),          // 8: pb.CombinationPayInfo
	(*JackPot)(nil),                     // 9: pb.JackPot
	(*BigWinMult)(nil),                  // 10: pb.BigWinMult
	(*SpinUserInfo)(nil),                // 11: pb.SpinUserInfo
	(*SpinResult_WinInfo)(nil),          // 12: pb.SpinResult.WinInfo
	(*SpinResult_WinInfo_LineInfo)(nil), // 13: pb.SpinResult.WinInfo.LineInfo
	(*SpinUserInfo_SpinUserBase)(nil),   // 14: pb.SpinUserInfo.SpinUserBase
	(*SpinUserInfo_LevelUpInfo)(nil),    // 15: pb.SpinUserInfo.LevelUpInfo
	(*Int32Array2)(nil),                 // 16: pb.Int32Array2
	(*Int32Array1)(nil),                 // 17: pb.Int32Array1
	(*RewardData)(nil),                  // 18: pb.RewardData
}
var file_slots_define_proto_depIdxs = []int32{
	16, // 0: pb.ReelsInfo.reelArray:type_name -> pb.Int32Array2
	16, // 1: pb.SpinResult.reelsArray:type_name -> pb.Int32Array2
	17, // 2: pb.SpinResult.posInReels:type_name -> pb.Int32Array1
	16, // 3: pb.SpinResult.results:type_name -> pb.Int32Array2
	17, // 4: pb.SpinResult.holdWins:type_name -> pb.Int32Array1
	16, // 5: pb.SpinResult.stopInfo:type_name -> pb.Int32Array2
	12, // 6: pb.SpinResult.winInfo:type_name -> pb.SpinResult.WinInfo
	7,  // 7: pb.PayInfo.cardsPayInfo:type_name -> pb.CardsPayInfo
	8,  // 8: pb.PayInfo.combinationPayInfo:type_name -> pb.CombinationPayInfo
	14, // 9: pb.SpinUserInfo.spinUserBase:type_name -> pb.SpinUserInfo.SpinUserBase
	15, // 10: pb.SpinUserInfo.levelUpInfo:type_name -> pb.SpinUserInfo.LevelUpInfo
	1,  // 11: pb.SpinResult.WinInfo.type:type_name -> pb.WinType
	13, // 12: pb.SpinResult.WinInfo.lines:type_name -> pb.SpinResult.WinInfo.LineInfo
	17, // 13: pb.SpinResult.WinInfo.LineInfo.positions:type_name -> pb.Int32Array1
	18, // 14: pb.SpinUserInfo.LevelUpInfo.reward:type_name -> pb.RewardData
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_slots_define_proto_init() }
func file_slots_define_proto_init() {
	if File_slots_define_proto != nil {
		return
	}
	file_common_define_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slots_define_proto_rawDesc), len(file_slots_define_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slots_define_proto_goTypes,
		DependencyIndexes: file_slots_define_proto_depIdxs,
		EnumInfos:         file_slots_define_proto_enumTypes,
		MessageInfos:      file_slots_define_proto_msgTypes,
	}.Build()
	File_slots_define_proto = out.File
	file_slots_define_proto_goTypes = nil
	file_slots_define_proto_depIdxs = nil
}
