// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDevAccount = "dev_account"

// DevAccount 开发模式的帐号信息表
type DevAccount struct {
	AccountID   int64  `gorm:"column:account_id;primaryKey;autoIncrement:true;comment:帐号id" json:"account_id"` // 帐号id
	AccountName string `gorm:"column:account_name;not null;comment:帐号名" json:"account_name"`                   // 帐号名
	Password    string `gorm:"column:password;not null;comment:密码" json:"password"`                            // 密码
	CreateIP    string `gorm:"column:create_ip;not null;comment:创建ip" json:"create_ip"`                        // 创建ip
	CreateTime  int64  `gorm:"column:create_time;not null;comment:创建时间" json:"create_time"`                    // 创建时间
}

// TableName DevAccount's table name
func (*DevAccount) TableName() string {
	return TableNameDevAccount
}
