// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLines4x6 = "lines4x6"

// Lines4x6 mapped from table <lines4x6>
type Lines4x6 struct {
	ID   int32  `gorm:"column:id" json:"id"`
	Line string `gorm:"column:line" json:"line"`
}

// TableName Lines4x6's table name
func (*Lines4x6) TableName() string {
	return TableNameLines4x6
}
