// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameN2CfgCard = "n2_cfg_card"

// N2CfgCard mapped from table <n2_cfg_card>
type N2CfgCard struct {
	Kid                  int32  `gorm:"column:kid;primaryKey;comment:keyid" json:"kid"`                                    // keyid
	ID                   int32  `gorm:"column:id;comment:ID" json:"id"`                                                    // ID
	RoomID               int32  `gorm:"column:room_id;comment:所属关卡" json:"room_id"`                                        // 所属关卡
	Cardindex            int32  `gorm:"column:cardindex;comment:物品序列" json:"cardindex"`                                    // 物品序列
	Cardchiname          string `gorm:"column:cardchiname;default:NULL;comment:物品中文名" json:"cardchiname"`                  // 物品中文名
	Cardengname          string `gorm:"column:cardengname;default:NULL;comment:物品英文名" json:"cardengname"`                  // 物品英文名
	Cardtype             int32  `gorm:"column:cardtype;comment:物品分类" json:"cardtype"`                                      // 物品分类
	CountNum             int32  `gorm:"column:count_num;comment:计数个数" json:"count_num"`                                    // 计数个数
	MirrorImageID        string `gorm:"column:mirror_image_id;comment:对应镜像ID" json:"mirror_image_id"`                      // 对应镜像ID
	IfBlocked            int32  `gorm:"column:if_blocked;comment:是否可被遮挡" json:"if_blocked"`                                // 是否可被遮挡
	Ifonbetline          int32  `gorm:"column:ifonbetline;comment:是否在押注线上" json:"ifonbetline"`                             // 是否在押注线上
	Cardwinnum           string `gorm:"column:cardwinnum;default:NULL;comment:一列算几个" json:"cardwinnum"`                    // 一列算几个
	Ifcontinue           int32  `gorm:"column:ifcontinue;comment:是否连续" json:"ifcontinue"`                                  // 是否连续
	WinSeq               string `gorm:"column:win_seq;default:NULL;comment:中奖顺序" json:"win_seq"`                           // 中奖顺序
	Rewardtype           int32  `gorm:"column:rewardtype;comment:中奖类型" json:"rewardtype"`                                  // 中奖类型
	Conditionargumentseq string `gorm:"column:conditionargumentseq;default:NULL;comment:条件参数" json:"conditionargumentseq"` // 条件参数
	IfCountOnNumber      int32  `gorm:"column:if_count_on_number;comment:是否按个数计数" json:"if_count_on_number"`               // 是否按个数计数
	Conditionoddsseq     string `gorm:"column:conditionoddsseq;default:NULL;comment:条件赔率" json:"conditionoddsseq"`         // 条件赔率
	MixedGroup           string `gorm:"column:mixed_group;default:NULL;comment:混合组" json:"mixed_group"`                    // 混合组
	MixedCondition       string `gorm:"column:mixed_condition;default:NULL;comment:混合组条件参数" json:"mixed_condition"`        // 混合组条件参数
	MixedOdds            string `gorm:"column:mixed_odds;default:NULL;comment:混合组条件赔率" json:"mixed_odds"`                  // 混合组条件赔率
	Conlittlegameidseq   string `gorm:"column:conlittlegameidseq;default:NULL;comment:条件小游戏" json:"conlittlegameidseq"`    // 条件小游戏
	Confreespinsseq      string `gorm:"column:confreespinsseq;default:NULL;comment:条件freespin" json:"confreespinsseq"`     // 条件freespin
	Rowrestrict          string `gorm:"column:rowrestrict;default:NULL;comment:可出现行" json:"rowrestrict"`                   // 可出现行
	Columnrestrict       string `gorm:"column:columnrestrict;default:NULL;comment:可出现列" json:"columnrestrict"`             // 可出现列
	Numrestrictonrow     int32  `gorm:"column:numrestrictonrow;comment:行上数目限制" json:"numrestrictonrow"`                    // 行上数目限制
	Numrestrictoncolumn  int32  `gorm:"column:numrestrictoncolumn;comment:列上数目限制" json:"numrestrictoncolumn"`              // 列上数目限制
	Width                int32  `gorm:"column:width;comment:宽度" json:"width"`                                              // 宽度
	Length               int32  `gorm:"column:length;comment:长度" json:"length"`                                            // 长度
	Ifallcolumn          int32  `gorm:"column:ifallcolumn;comment:是否占满一列" json:"ifallcolumn"`                              // 是否占满一列
	Isreplacable         int32  `gorm:"column:isreplacable;comment:是否可被代替" json:"isreplacable"`                            // 是否可被代替
	Replacefunction      int32  `gorm:"column:replacefunction;comment:是否有代替功能" json:"replacefunction"`                     // 是否有代替功能
	Cardlife             int32  `gorm:"column:cardlife;comment:生效期" json:"cardlife"`                                       // 生效期
	GamePicSuf           string `gorm:"column:game_pic_suf;default:NULL;comment:图片资源对应" json:"game_pic_suf"`               // 图片资源对应
	Isspcount            int16  `gorm:"column:isspcount" json:"isspcount"`
}

// TableName N2CfgCard's table name
func (*N2CfgCard) TableName() string {
	return TableNameN2CfgCard
}
