// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameN2CfgLevel = "n2_cfg_level"

// N2CfgLevel mapped from table <n2_cfg_level>
type N2CfgLevel struct {
	Kid                int32   `gorm:"column:kid;primaryKey;comment:keyid" json:"kid"`                       // keyid
	ID                 int32   `gorm:"column:id;comment:ID" json:"id"`                                       // ID
	Levelid            int32   `gorm:"column:levelid;not null;comment:等级" json:"levelid"`                    // 等级
	Exp                string  `gorm:"column:exp;comment:本级升级经验" json:"exp"`                                 // 本级升级经验
	Totalexp           string  `gorm:"column:totalexp;comment:累计升级经验" json:"totalexp"`                       // 累计升级经验
	Minbet             int64   `gorm:"column:minbet;comment:最小押注额" json:"minbet"`                            // 最小押注额
	Recommendbet       int64   `gorm:"column:recommendbet;comment:推荐押注" json:"recommendbet"`                 // 推荐押注
	Maxbet             int64   `gorm:"column:maxbet;comment:最大押注倍率" json:"maxbet"`                           // 最大押注倍率
	Coinbonus          int64   `gorm:"column:coinbonus;comment:升级送金币" json:"coinbonus"`                      // 升级送金币
	Coinamount         int64   `gorm:"column:coinamount;comment:领取金币数量" json:"coinamount"`                   // 领取金币数量
	Dailymessagereward int64   `gorm:"column:dailymessagereward;comment:每日官方邮件奖励" json:"dailymessagereward"` // 每日官方邮件奖励
	Givencoinamount    int64   `gorm:"column:givencoinamount;comment:可领取好友金币" json:"givencoinamount"`        // 可领取好友金币
	Basepigcoin        int64   `gorm:"column:basepigcoin;comment:小猪基础金币数" json:"basepigcoin"`                // 小猪基础金币数
	Maxpigcoin         int64   `gorm:"column:maxpigcoin;comment:小猪金币储存上限" json:"maxpigcoin"`                 // 小猪金币储存上限
	Facebookcoins      int64   `gorm:"column:facebookcoins;comment:facebook分享赠送金币" json:"facebookcoins"`     // facebook分享赠送金币
	Dailysharinglimits int32   `gorm:"column:dailysharinglimits;comment:每日最大分享次数" json:"dailysharinglimits"` // 每日最大分享次数
	Basegoldpig        int64   `gorm:"column:basegoldpig;comment:金猪基础金币数" json:"basegoldpig"`                // 金猪基础金币数
	Maxgoldpig         int64   `gorm:"column:maxgoldpig;comment:金猪金币储存上限" json:"maxgoldpig"`                 // 金猪金币储存上限
	Stakegear          string  `gorm:"column:stakegear;comment:押注档位" json:"stakegear"`                       // 押注档位
	Basediamondpig     int64   `gorm:"column:basediamondpig;comment:钻石猪基础金币数" json:"basediamondpig"`         // 钻石猪基础金币数
	Maxdiamondpig      int64   `gorm:"column:maxdiamondpig;comment:钻石猪金币储存上限" json:"maxdiamondpig"`          // 钻石猪金币储存上限
	OtherprizeType     string  `gorm:"column:otherprize_type;comment:其他奖励类型" json:"otherprize_type"`         // 其他奖励类型
	OtherprizeNum      string  `gorm:"column:otherprize_num;comment:其他奖励数量" json:"otherprize_num"`           // 其他奖励数量
	UnlockRoom         int64   `gorm:"column:unlock_room" json:"unlock_room"`
	Pigsave            float32 `gorm:"column:pigsave;default:1" json:"pigsave"`
	Goldpigsave        float32 `gorm:"column:goldpigsave;default:1" json:"goldpigsave"`
	Diamondpigsave     float32 `gorm:"column:diamondpigsave;default:1" json:"diamondpigsave"`
}

// TableName N2CfgLevel's table name
func (*N2CfgLevel) TableName() string {
	return TableNameN2CfgLevel
}
