// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlayer = "player"

// Player 玩家角色表
type Player struct {
	PlayerID       int64  `gorm:"column:player_id;primaryKey;comment:角色id" json:"player_id"`                  // 角色id
	Pid            int32  `gorm:"column:pid;not null;comment:平台id" json:"pid"`                                // 平台id
	OpenID         string `gorm:"column:open_id;not null;comment:平台open_id" json:"open_id"`                   // 平台open_id
	UID            int64  `gorm:"column:uid;not null;comment:用户id" json:"uid"`                                // 用户id
	ServerID       int32  `gorm:"column:server_id;not null;comment:创角时的游戏服id" json:"server_id"`               // 创角时的游戏服id
	MergedServerID int32  `gorm:"column:merged_server_id;not null;comment:合服后的游戏服id" json:"merged_server_id"` // 合服后的游戏服id
	PlayerName     string `gorm:"column:player_name;not null;comment:角色名称" json:"player_name"`                // 角色名称
	Gender         int32  `gorm:"column:gender;not null;comment:角色性别" json:"gender"`                          // 角色性别
	Level          int32  `gorm:"column:level;not null;comment:角色等级" json:"level"`                            // 角色等级
	Exp            int64  `gorm:"column:exp;not null;comment:角色经验" json:"exp"`                                // 角色经验
	CreateTime     int64  `gorm:"column:create_time;not null;comment:创建时间" json:"create_time"`                // 创建时间
}

// TableName Player's table name
func (*Player) TableName() string {
	return TableNamePlayer
}
