// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLines3x3 = "lines3x3"

// Lines3x3 mapped from table <lines3x3>
type Lines3x3 struct {
	ID   int32  `gorm:"column:id" json:"id"`
	Line string `gorm:"column:line" json:"line"`
}

// TableName Lines3x3's table name
func (*Lines3x3) TableName() string {
	return TableNameLines3x3
}
