// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLinesID = "newsz_2024.lines_ids"

// LinesID mapped from table <lines_ids>
type LinesID struct {
	Xy  string `gorm:"column:xy;primaryKey" json:"xy"`
	Ids string `gorm:"column:ids" json:"ids"`
}

// TableName LinesID's table name
func (*LinesID) TableName() string {
	return TableNameLinesID
}
