// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLines3x4 = "newsz_2024.lines3x4"

// Lines3x4 mapped from table <lines3x4>
type Lines3x4 struct {
	ID   int32  `gorm:"column:id" json:"id"`
	Line string `gorm:"column:line" json:"line"`
}

// TableName Lines3x4's table name
func (*Lines3x4) TableName() string {
	return TableNameLines3x4
}
