// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLines4x3 = "newsz_2024.lines4x3"

// Lines4x3 mapped from table <lines4x3>
type Lines4x3 struct {
	ID   int32  `gorm:"column:id" json:"id"`
	Line string `gorm:"column:line" json:"line"`
}

// TableName Lines4x3's table name
func (*Lines4x3) TableName() string {
	return TableNameLines4x3
}
