// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLines3x5 = "newsz_2024.lines3x5"

// Lines3x5 mapped from table <lines3x5>
type Lines3x5 struct {
	ID   int32  `gorm:"column:id" json:"id"`
	Line string `gorm:"column:line" json:"line"`
}

// TableName Lines3x5's table name
func (*Lines3x5) TableName() string {
	return TableNameLines3x5
}
