// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLines3x6 = "lines3x6"

// Lines3x6 mapped from table <lines3x6>
type Lines3x6 struct {
	ID   int32  `gorm:"column:id" json:"id"`
	Line string `gorm:"column:line" json:"line"`
}

// TableName Lines3x6's table name
func (*Lines3x6) TableName() string {
	return TableNameLines3x6
}
