// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLines4x5 = "newsz_2024.lines4x5"

// Lines4x5 mapped from table <lines4x5>
type Lines4x5 struct {
	ID   int32  `gorm:"column:id" json:"id"`
	Line string `gorm:"column:line" json:"line"`
}

// TableName Lines4x5's table name
func (*Lines4x5) TableName() string {
	return TableNameLines4x5
}
