// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLines5x5 = "newsz_2024.lines5x5"

// Lines5x5 mapped from table <lines5x5>
type Lines5x5 struct {
	ID   int32  `gorm:"column:id" json:"id"`
	Line string `gorm:"column:line;default:NULL" json:"line"`
}

// TableName Lines5x5's table name
func (*Lines5x5) TableName() string {
	return TableNameLines5x5
}
