// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameN2CfgRoomlist = "n2_cfg_roomlist"

// N2CfgRoomlist mapped from table <n2_cfg_roomlist>
type N2CfgRoomlist struct {
	Kid                   int32   `gorm:"column:kid;primaryKey;comment:keyid" json:"kid"`                                         // keyid
	ID                    int32   `gorm:"column:id;comment:ID" json:"id"`                                                         // ID
	RoomID                int32   `gorm:"column:room_id;comment:关卡ID" json:"room_id"`                                             // 关卡ID
	RoomName              string  `gorm:"column:room_name;comment:关卡名称" json:"room_name"`                                         // 关卡名称
	LevelUnlock           int32   `gorm:"column:level_unlock;comment:等级限制" json:"level_unlock"`                                   // 等级限制
	RoomIndex             int32   `gorm:"column:room_index;comment:房间显示位置" json:"room_index"`                                     // 房间显示位置
	RecommendIconFunlabel int32   `gorm:"column:recommend_icon_funlabel;comment:图标标签（长条和普通同时）" json:"recommend_icon_funlabel"`    // 图标标签（长条和普通同时）
	VipFirst              int32   `gorm:"column:vip_first;comment:vip体验" json:"vip_first"`                                        // vip体验
	RoomIconShowlable     int32   `gorm:"column:room_icon_showlable;comment:关卡特殊标签展示（open to all 这类）" json:"room_icon_showlable"` // 关卡特殊标签展示（open to all 这类）
	Axisx                 float64 `gorm:"column:axisx;comment:横轴长度" json:"axisx"`                                                 // 横轴长度
	Axisy                 float64 `gorm:"column:axisy;comment:纵轴长度" json:"axisy"`                                                 // 纵轴长度
	LineMin               int32   `gorm:"column:line_min;comment:最小线个数" json:"line_min"`                                          // 最小线个数
	LineMax               int32   `gorm:"column:line_max;comment:最大线个数" json:"line_max"`                                          // 最大线个数
	Linesequence          string  `gorm:"column:linesequence;comment:线序列" json:"linesequence"`                                    // 线序列
	Islinevisible         int32   `gorm:"column:islinevisible;comment:是否显示线标记" json:"islinevisible"`                              // 是否显示线标记
	AccessTimeRange       string  `gorm:"column:access_time_range" json:"access_time_range"`
	Betbaseamount         int64   `gorm:"column:betbaseamount;comment:下注基础金额" json:"betbaseamount"`                            // 下注基础金额
	Roundawardspin        int64   `gorm:"column:roundawardspin;comment:关卡奖励freespin" json:"roundawardspin"`                    // 关卡奖励freespin
	Tournamentid          int32   `gorm:"column:tournamentid;comment:对应TournamentID" json:"tournamentid"`                      // 对应TournamentID
	SfxMidwin             int32   `gorm:"column:sfx_midwin;comment:结算时倍率：中档（针对数值框使用）" json:"sfx_midwin"`                       // 结算时倍率：中档（针对数值框使用）
	SfxBigwin             int32   `gorm:"column:sfx_bigwin;comment:结算时倍率：高档（针对数值框使用）" json:"sfx_bigwin"`                       // 结算时倍率：高档（针对数值框使用）
	Bigthreshold          int64   `gorm:"column:bigthreshold;comment:BIG阈值" json:"bigthreshold"`                               // BIG阈值
	Megathreshold         int64   `gorm:"column:megathreshold;comment:MEGA阈值" json:"megathreshold"`                            // MEGA阈值
	Superthreshold        int64   `gorm:"column:superthreshold;comment:SUPER阈值" json:"superthreshold"`                         // SUPER阈值
	Epicthreshold         int64   `gorm:"column:epicthreshold;comment:EPIC阈值" json:"epicthreshold"`                            // EPIC阈值
	IfGetmorespin         int32   `gorm:"column:if_getmorespin;comment:是否在freespin下可以再中freespin" json:"if_getmorespin"`        // 是否在freespin下可以再中freespin
	FreespinTimesRange    int32   `gorm:"column:freespin_times_range;comment:freespin次数范围" json:"freespin_times_range"`        // freespin次数范围
	FreespinMultiplier    int32   `gorm:"column:freespin_multiplier;comment:freespin使用倍率" json:"freespin_multiplier"`          // freespin使用倍率
	CardCollectID         int32   `gorm:"column:card_collect_id;comment:收集卡牌ID" json:"card_collect_id"`                        // 收集卡牌ID
	Collectnumrequied     int32   `gorm:"column:collectnumrequied;comment:要求收集个数" json:"collectnumrequied"`                    // 要求收集个数
	Cardsequence          string  `gorm:"column:cardsequence;comment:物品序列" json:"cardsequence"`                                // 物品序列
	IconResAddr           string  `gorm:"column:icon_res_addr;comment:图标资源地址" json:"icon_res_addr"`                            // 图标资源地址
	GameResAddr           string  `gorm:"column:game_res_addr;comment:游戏资源地址" json:"game_res_addr"`                            // 游戏资源地址
	BillingID             string  `gorm:"column:billing_id;comment:计费点id" json:"billing_id"`                                   // 计费点id
	RoomShowstate         int32   `gorm:"column:room_showstate;comment:房间状态" json:"room_showstate"`                            // 房间状态
	UnlockType            int32   `gorm:"column:unlock_type;comment:解锁类型" json:"unlock_type"`                                  // 解锁类型
	CollectAmount         string  `gorm:"column:collect_amount;comment:收集个数" json:"collect_amount"`                            // 收集个数
	CoinsRequied          string  `gorm:"column:coins_requied;comment:最低触发金币" json:"coins_requied"`                            // 最低触发金币
	CollectPricerate      string  `gorm:"column:collect_pricerate;comment:收集中奖倍率" json:"collect_pricerate"`                    // 收集中奖倍率
	CollectConvertrate    string  `gorm:"column:collect_convertrate;comment:累计折算比率" json:"collect_convertrate"`                // 累计折算比率
	CollectTimeMultiplier string  `gorm:"column:collect_time_multiplier;comment:收集的时间奖励" json:"collect_time_multiplier"`       // 收集的时间奖励
	CollectRequiedtime    string  `gorm:"column:collect_requiedtime;comment:收集要求时间" json:"collect_requiedtime"`                // 收集要求时间
	AcquiredSpinTimes     string  `gorm:"column:acquired_spin_times;comment:要求spin次数" json:"acquired_spin_times"`              // 要求spin次数
	Acquired5Ofkind       string  `gorm:"column:acquired_5ofkind;comment:要求5ofkind次数" json:"acquired_5ofkind"`                 // 要求5ofkind次数
	Acquired33            string  `gorm:"column:acquired_33;comment:要求3×3次数" json:"acquired_33"`                               // 要求3×3次数
	WildRange             string  `gorm:"column:wild_range;comment:wild中奖倍率范围" json:"wild_range"`                              // wild中奖倍率范围
	Version               int32   `gorm:"column:version;comment:数值版本" json:"version"`                                          // 数值版本
	BetDisplay            string  `gorm:"column:bet_display;comment:倍率选择界面展示的档位" json:"bet_display"`                           // 倍率选择界面展示的档位
	BetDisplayButtonType  int32   `gorm:"column:bet_display_button_type;comment:倍率选择界面展示的档位标签" json:"bet_display_button_type"` // 倍率选择界面展示的档位标签
	BetUnlockCondition    string  `gorm:"column:bet_unlock_condition;comment:倍率档位解锁需要的等级" json:"bet_unlock_condition"`         // 倍率档位解锁需要的等级
	BetStakegear          int32   `gorm:"column:bet_stakegear;comment:押注档位翻倍倍数" json:"bet_stakegear"`                          // 押注档位翻倍倍数
	IsGlobalJackpot       string  `gorm:"column:is_global_jackpot;comment:标记第几档是全局Jackpot" json:"is_global_jackpot"`           // 标记第几档是全局Jackpot
	Note                  string  `gorm:"column:note;comment:关卡说明" json:"note"`                                                // 关卡说明
	CoinsbetRequied       string  `gorm:"column:coinsbet_requied" json:"coinsbet_requied"`
	ChooseNum             int16   `gorm:"column:choose_num" json:"choose_num"`
	BetDisplay2           string  `gorm:"column:bet_display2" json:"bet_display2"`
}

// TableName N2CfgRoomlist's table name
func (*N2CfgRoomlist) TableName() string {
	return TableNameN2CfgRoomlist
}
