// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameDomainOutbox = "newsz_2024.domain_outbox"

// DomainOutbox mapped from table <newsz_2024.domain_outbox>
type DomainOutbox struct {
	EventID       string `gorm:"column:event_id;primaryKey" json:"event_id"`
	AggregateType string `gorm:"column:aggregate_type;not null" json:"aggregate_type"`
	AggregateID   string `gorm:"column:aggregate_id;not null" json:"aggregate_id"`
	EventType     string `gorm:"column:event_type;not null" json:"event_type"`
	// JSON is a driver.Valuer: PostgreSQL receives JSON text rather than a
	// []byte/bytea parameter.  This is required for a JSONB column.
	Payload       datatypes.JSON `gorm:"column:payload;type:jsonb;not null" json:"payload"`
	Status        string         `gorm:"column:status;not null;default:PENDING" json:"status"`
	RetryCount    int32          `gorm:"column:retry_count;not null" json:"retry_count"`
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	PublishedAt   time.Time      `gorm:"column:published_at" json:"published_at"`
	LockedBy      string         `gorm:"column:locked_by" json:"locked_by"`
	LockedUntil   time.Time      `gorm:"column:locked_until" json:"locked_until"`
	NextAttemptAt time.Time      `gorm:"column:next_attempt_at" json:"next_attempt_at"`
	LastError     string         `gorm:"column:last_error" json:"last_error"`
}

// TableName DomainOutbox's table name
func (*DomainOutbox) TableName() string {
	return TableNameDomainOutbox
}
