// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAssetOperation = "newsz_2024.asset_operation"

// AssetOperation mapped from table <newsz_2024.asset_operation>
type AssetOperation struct {
	OperationID     string    `gorm:"column:operation_id;primaryKey" json:"operation_id"`
	UserID          int64     `gorm:"column:user_id;not null" json:"user_id"`
	OperationType   string    `gorm:"column:operation_type;not null" json:"operation_type"`
	RequestID       string    `gorm:"column:request_id;not null" json:"request_id"`
	Status          string    `gorm:"column:status;not null" json:"status"`
	ResponseCode    int32     `gorm:"column:response_code;not null" json:"response_code"`
	ResponsePayload []uint8   `gorm:"column:response_payload" json:"response_payload"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	CompletedAt     time.Time `gorm:"column:completed_at" json:"completed_at"`
}

// TableName AssetOperation's table name
func (*AssetOperation) TableName() string {
	return TableNameAssetOperation
}
