// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAssetLedger = "newsz_2024.asset_ledger"

// AssetLedger mapped from table <newsz_2024.asset_ledger>
type AssetLedger struct {
	LedgerID     int64     `gorm:"column:ledger_id;primaryKey;autoIncrement:true" json:"ledger_id"`
	OperationID  string    `gorm:"column:operation_id;not null" json:"operation_id"`
	UserID       int64     `gorm:"column:user_id;not null" json:"user_id"`
	AssetKind    string    `gorm:"column:asset_kind;not null" json:"asset_kind"`
	Delta        int64     `gorm:"column:delta;not null" json:"delta"`
	BalanceAfter int64     `gorm:"column:balance_after;not null" json:"balance_after"`
	Reason       string    `gorm:"column:reason;not null" json:"reason"`
	SourceType   string    `gorm:"column:source_type;not null" json:"source_type"`
	SourceID     string    `gorm:"column:source_id;not null" json:"source_id"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName AssetLedger's table name
func (*AssetLedger) TableName() string {
	return TableNameAssetLedger
}
