// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSlotsDevice = "slots_device"

// SlotsDevice mapped from table <slots_device>
type SlotsDevice struct {
	DeviceID              int32     `gorm:"column:device_id;primaryKey;autoIncrement:true" json:"device_id"`
	DeviceName            string    `gorm:"column:device_name;not null;comment:用户唯一标示" json:"device_name"` // 用户唯一标示
	EmailID               int32     `gorm:"column:email_id;comment:绑定邮箱的id" json:"email_id"`               // 绑定邮箱的id
	UserID                int32     `gorm:"column:user_id" json:"user_id"`
	IsLogin               bool      `gorm:"column:is_login;comment:登录状态-在线推送（待定）" json:"is_login"`                           // 登录状态-在线推送（待定）
	PushToken             string    `gorm:"column:push_token;comment:推送id-客户推送（第三方SD-OneSingle,客户端传送过来）" json:"push_token"`  // 推送id-客户推送（第三方SD-OneSingle,客户端传送过来）
	Platform              int32     `gorm:"column:platform;not null;comment:平台-ios=1 android=2 web=4 aws=5" json:"platform"` // 平台-ios=1 android=2 web=4 aws=5
	LoginTime             time.Time `gorm:"column:login_time" json:"login_time"`
	CountryCode           string    `gorm:"column:country_code;comment:国家代码(ip去取，库guip)" json:"country_code"`     // 国家代码(ip去取，库guip)
	ClientTimezone        string    `gorm:"column:client_timezone;default:0;comment:用户时区" json:"client_timezone"` // 用户时区
	ClientIP              string    `gorm:"column:client_ip;comment:ip地址-不区分代理地址，如需要由客端传递" json:"client_ip"`      // ip地址-不区分代理地址，如需要由客端传递
	CurVer                string    `gorm:"column:cur_ver;comment:当前版本-最新版？？？" json:"cur_ver"`                    // 当前版本-最新版？？？
	LastVer               string    `gorm:"column:last_ver;comment:上个版本" json:"last_ver"`                         // 上个版本
	CollectNewGift        bool      `gorm:"column:collect_new_gift;comment:是否收集了新设备礼物" json:"collect_new_gift"`   // 是否收集了新设备礼物
	HotVersion            string    `gorm:"column:hot_version;comment:热更新版本" json:"hot_version"`                  // 热更新版本
	InstallChannel        string    `gorm:"column:install_channel;comment:安装渠道" json:"install_channel"`           // 安装渠道
	OsVersion             string    `gorm:"column:os_version;comment:机型" json:"os_version"`                       // 机型
	PhoneNumModel         string    `gorm:"column:phone_num_model" json:"phone_num_model"`
	UserAgreeServiceTerms bool      `gorm:"column:user_agree_service_terms;comment:是否同意了协议条款" json:"user_agree_service_terms"` // 是否同意了协议条款
	AdjustAdid            string    `gorm:"column:adjust_adid;comment:adjust相关统计id" json:"adjust_adid"`                        // adjust相关统计id
	AdjustIdfa            string    `gorm:"column:adjust_idfa;comment:adjust相关id" json:"adjust_idfa"`                          // adjust相关id
	AdjustGpsAdid         string    `gorm:"column:adjust_gps_adid;comment:adjust相关ID" json:"adjust_gps_adid"`                  // adjust相关ID
	FbSource              string    `gorm:"column:fb_source;comment:fb的来源" json:"fb_source"`                                   // fb的来源
	City                  string    `gorm:"column:city;comment:城市" json:"city"`                                                // 城市
	Timezone              string    `gorm:"column:timezone;comment:时区" json:"timezone"`                                        // 时区
	TimezoneOffset        float32   `gorm:"column:timezone_offset" json:"timezone_offset"`
	Latitude              float32   `gorm:"column:latitude;comment:纬度" json:"latitude"`                     // 纬度
	Longitude             float32   `gorm:"column:longitude;comment:经度" json:"longitude"`                   // 经度
	CreateTime            time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`             // 创建时间
	PackageName           string    `gorm:"column:package_name;comment:包名" json:"package_name"`             // 包名
	DeviceInfo            string    `gorm:"column:device_info;comment:设备信息" json:"device_info"`             // 设备信息
	IsComment             bool      `gorm:"column:is_comment;comment:是否评论" json:"is_comment"`               // 是否评论
	CommentTimes          int32     `gorm:"column:comment_times;comment:弹评论次数" json:"comment_times"`        // 弹评论次数
	UpdatedTimezone       bool      `gorm:"column:updated_timezone;comment:是否更新时区" json:"updated_timezone"` // 是否更新时区
	URLParams             string    `gorm:"column:url_params" json:"url_params"`
	Referrer              string    `gorm:"column:referrer" json:"referrer"`
	FbQuery               string    `gorm:"column:fb_query;comment:fb参数" json:"fb_query"` // fb参数
	AdjustAdidMd5         string    `gorm:"column:adjust_adid_md5;default:-" json:"adjust_adid_md5"`
	AdjustIdfaMd5         string    `gorm:"column:adjust_idfa_md5;default:-" json:"adjust_idfa_md5"`
	AdjustGpsAdidMd5      string    `gorm:"column:adjust_gps_adid_md5;default:-" json:"adjust_gps_adid_md5"`
	AdjustIsRas           int32     `gorm:"column:adjust_is_ras" json:"adjust_is_ras"`
	AdjustInfo            *string   `gorm:"column:adjust_info" json:"adjust_info"`
	LastLoginTime         time.Time `gorm:"column:last_login_time;comment:上一次登录时间" json:"last_login_time"` // 上一次登录时间
	FbInstallReferrer     *string   `gorm:"column:fb_install_referrer" json:"fb_install_referrer"`
	ClientDeviceInfo      *string   `gorm:"column:client_device_info" json:"client_device_info"`
	IPInfo                *string   `gorm:"column:ip_info" json:"ip_info"`
	Password              string    `gorm:"column:password;comment:用户密码" json:"password"` // 用户密码
}

// TableName SlotsDevice's table name
func (*SlotsDevice) TableName() string {
	return TableNameSlotsDevice
}
