/*
 * @Author: t 921865806@qq.com
 * @Date: 2025-11-17 11:27:10
 * @LastEditors: t 921865806@qq.com
 * @LastEditTime: 2025-11-27 16:04:22
 * @FilePath: /examples/demo_cluster/nodes/center/model/slots_user.gen.go
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSlotsUser = "slots_user"

// SlotsUser mapped from table <slots_user>
type SlotsUser struct {
	UserID            int32     `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	PlayerGroup       int32     `gorm:"column:player_group;comment:用户分组" json:"player_group"`                  // 用户分组
	UserType          int32     `gorm:"column:user_type;comment:用户分类" json:"user_type"`                        // 用户分类
	UserName          string    `gorm:"column:user_name;comment:名字" json:"user_name"`                          // 名字
	Money             float64   `gorm:"column:money;comment:金币" json:"money"`                                  // 金币
	Diamond           int64     `gorm:"column:diamond;comment:钻石" json:"diamond"`                              // 钻石
	ScratchNum        int32     `gorm:"column:scratch_num;comment:刮刮卡" json:"scratch_num"`                     // 刮刮卡
	UserLevel         int32     `gorm:"column:user_level;comment:等级" json:"user_level"`                        // 等级
	CurExp            string    `gorm:"column:cur_exp;default:0;comment:当前经验值" json:"cur_exp"`                 // 当前经验值
	HonorLevel        int32     `gorm:"column:honor_level;comment:vip" json:"honor_level"`                     // vip
	HonorExp          int64     `gorm:"column:honor_exp;comment:当前VIP等级经验值" json:"honor_exp"`                  // 当前VIP等级经验值
	Sex               int32     `gorm:"column:sex;comment:性别1男2女" json:"sex"`                                  // 性别1男2女
	Icon              string    `gorm:"column:icon;comment:头像地址" json:"icon"`                                  // 头像地址
	ThirdIcon         string    `gorm:"column:third_icon;comment:第三方头像地址" json:"third_icon"`                   // 第三方头像地址
	MobilePhone       string    `gorm:"column:mobile_phone;comment:手机" json:"mobile_phone"`                    // 手机
	Birthday          string    `gorm:"column:birthday;default:0;comment:生日" json:"birthday"`                  // 生日
	AdIsOpen          bool      `gorm:"column:ad_is_open;default:true;comment:广告是否开启" json:"ad_is_open"`       // 广告是否开启
	AdDisplayNum      int32     `gorm:"column:ad_display_num;comment:广告观看完成总次数" json:"ad_display_num"`         // 广告观看完成总次数
	AdGainMoney       int64     `gorm:"column:ad_gain_money;comment:广告获得金币" json:"ad_gain_money"`              // 广告获得金币
	PayAllMoney       float32   `gorm:"column:pay_all_money;comment:付费总额(分)" json:"pay_all_money"`             // 付费总额(分)
	PayNum            int32     `gorm:"column:pay_num;comment:付费次数" json:"pay_num"`                            // 付费次数
	IsReplenish       bool      `gorm:"column:is_replenish;comment:是否补全信息" json:"is_replenish"`                // 是否补全信息
	LastLoginType     int32     `gorm:"column:last_login_type;comment:最后登录方式" json:"last_login_type"`          // 最后登录方式
	LastLoginPlatform int32     `gorm:"column:last_login_platform;comment:最后登录的平台" json:"last_login_platform"` // 最后登录的平台
	LoginCount        int32     `gorm:"column:login_count;comment:登录次数" json:"login_count"`                    // 登录次数
	LogoutTime        time.Time `gorm:"column:logout_time;comment:退出游戏时间" json:"logout_time"`                  // 退出游戏时间
	CreateTime        time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                    // 创建时间
	LoginTime         time.Time `gorm:"column:login_time;comment:最后登录时间录时间" json:"login_time"`                 // 最后登录时间录时间
	LoginStamp        time.Time `gorm:"column:login_stamp" json:"login_stamp"`
	AdStartNum        int32     `gorm:"column:ad_start_num;comment:广告点击次数" json:"ad_start_num"` // 广告点击次数
	BindEmail         string    `gorm:"column:bind_email;comment:绑定邮箱" json:"bind_email"`       // 绑定邮箱
	AdAllMoney        float32   `gorm:"column:ad_all_money" json:"ad_all_money"`
	LastLoginTime     time.Time `gorm:"column:last_login_time;comment:上一次登录时间" json:"last_login_time"` // 上一次登录时间
	AdjustIsGroup     int32     `gorm:"column:adjust_is_group" json:"adjust_is_group"`
	BeforePlayerGroup int32     `gorm:"column:before_player_group" json:"before_player_group"`
	AdSafeMark        int32     `gorm:"column:ad_safe_mark;default:1" json:"ad_safe_mark"`
	ExpPercent        float64   `gorm:"column:exp_percent;default:-1;comment:经验比" json:"exp_percent"` // 经验比
}

// TableName SlotsUser's table name
func (*SlotsUser) TableName() string {
	return TableNameSlotsUser
}
