// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserBind = "user_bind"

// UserBind mapped from table <user_bind>
type UserBind struct {
	UserID   int32     `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:用户id" json:"user_id"` // 用户id
	SdkID    int32     `gorm:"column:sdk_id;comment:sdk配置id" json:"sdk_id"`                              // sdk配置id
	Pid      int32     `gorm:"column:pid;comment:平台id" json:"pid"`                                       // 平台id
	OpenID   string    `gorm:"column:open_id;comment:平台帐号open_id" json:"open_id"`                        // 平台帐号open_id
	UpTime   time.Time `gorm:"column:up_time;comment:最后一次更新时间" json:"up_time"`                           // 最后一次更新时间
	BindTime time.Time `gorm:"column:bind_time;comment:绑定时间" json:"bind_time"`                           // 绑定时间
}

// TableName UserBind's table name
func (*UserBind) TableName() string {
	return TableNameUserBind
}
