/*
 * @Author: t 921865806@qq.com
 * @Date: 2025-11-18 23:32:22
 * @LastEditors: t 921865806@qq.com
 * @LastEditTime: 2025-12-26 11:30:43
 * @FilePath: /examples/demo_cluster/internal/model/user_bind.gen.go
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserBind = "newsz_2024.user_bind"

// UserBind mapped from table <user_bind>
type UserBind struct {
	UserID   int32     `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:用户id" json:"user_id"` // 用户id
	SdkID    int32     `gorm:"column:sdk_id;comment:sdk配置id" json:"sdk_id"`                              // sdk配置id
	Pid      int32     `gorm:"column:pid;comment:平台id" json:"pid"`                                       // 平台id
	OpenID   string    `gorm:"column:open_id;comment:平台帐号open_id" json:"open_id"`                        // 平台帐号open_id
	UpTime   time.Time `gorm:"column:up_time;comment:最后一次更新时间" json:"up_time"`                           // 最后一次更新时间
	BindTime time.Time `gorm:"column:bind_time;comment:绑定时间" json:"bind_time"`                           // 绑定时间
}

// TableName UserBind's table name
func (*UserBind) TableName() string {
	return TableNameUserBind
}
